### ISSUE TITLE
Please upgrade POM to use recent version of your libraries.

### ISSUE THREAD

**Issue by mt3o** [hpe-idol/java-idol-types#3]
There is dependency like:
`
        <dependency>
            <groupId>com.hp.autonomy.frontend</groupId>
            <artifactId>aci-types</artifactId>
            <version>0.22.0</version>
        </dependency>
`
However oldest version of package on GitHub is 1...

Compare with: https://github.com/hpe-idol/java-idol-utils/commit/f1ca3819aa1162699e6f211b135df70187193879

**Comment by tung-jin-chew-hp** [comment]
I think the oldest version on Github is 0.22.0, see https://github.com/hpe-idol/java-aci-types. Closing for now, please reopen if you think differently.
